python3.12 extend4.py ../../moot/optimize/config/wc+rs-3d-c4-obj1.csv | tee results/wc+rs-3d-c4-obj1.csv
python3.12 extend4.py ../../moot/optimize/config/wc+sol-3d-c4-obj1.csv | tee results/wc+sol-3d-c4-obj1.csv
python3.12 extend4.py ../../moot/optimize/config/wc+wc-3d-c4-obj1.csv | tee results/wc+wc-3d-c4-obj1.csv
python3.12 extend4.py ../../moot/optimize/config/SS-D.csv | tee results/SS-D.csv
python3.12 extend4.py ../../moot/optimize/config/SS-F.csv | tee results/SS-F.csv
python3.12 extend4.py ../../moot/optimize/config/SS-G.csv | tee results/SS-G.csv
python3.12 extend4.py ../../moot/optimize/config/SS-B.csv | tee results/SS-B.csv
python3.12 extend4.py ../../moot/optimize/config/SS-E.csv | tee results/SS-E.csv
python3.12 extend4.py ../../moot/optimize/config/SS-A.csv | tee results/SS-A.csv
python3.12 extend4.py ../../moot/optimize/config/SS-C.csv | tee results/SS-C.csv
python3.12 extend4.py ../../moot/optimize/config/SS-H.csv | tee results/SS-H.csv
python3.12 extend4.py ../../moot/optimize/config/SS-I.csv | tee results/SS-I.csv
python3.12 extend4.py ../../moot/optimize/misc/auto93.csv | tee results/auto93.csv
python3.12 extend4.py ../../moot/optimize/config/sol-6d-c2-obj1.csv | tee results/sol-6d-c2-obj1.csv
python3.12 extend4.py ../../moot/optimize/config/wc-6d-c1-obj1.csv | tee results/wc-6d-c1-obj1.csv
python3.12 extend4.py ../../moot/optimize/config/rs-6d-c3_obj1.csv | tee results/rs-6d-c3_obj1.csv
python3.12 extend4.py ../../moot/optimize/config/rs-6d-c3_obj2.csv | tee results/rs-6d-c3_obj2.csv
python3.12 extend4.py ../../moot/optimize/config/SS-K.csv | tee results/SS-K.csv
python3.12 extend4.py ../../moot/optimize/config/SS-J.csv | tee results/SS-J.csv
python3.12 extend4.py ../../moot/optimize/config/SS-S.csv | tee results/SS-S.csv
python3.12 extend4.py ../../moot/optimize/config/Apache_AllMeasurements.csv | tee results/Apache_AllMeasurements.csv
python3.12 extend4.py ../../moot/optimize/process/pom3d.csv | tee results/pom3d.csv

python3.12 extend4.py ../../moot/optimize/hpo/healthCloseIsses12mths0001-hard.csv | tee results/healthCloseIsses12mths0001-hard.csv
python3.12 extend4.py ../../moot/optimize/hpo/healthCloseIsses12mths0011-easy.csv | tee results/healthCloseIsses12mths0011-easy.csv
python3.12 extend4.py ../../moot/optimize/misc/Wine_quality.csv | tee results/Wine_quality.csv
python3.12 extend4.py ../../moot/optimize/config/SS-O.csv | tee results/SS-O.csv
python3.12 extend4.py ../../moot/optimize/config/SS-L.csv | tee results/SS-L.csv
python3.12 extend4.py ../../moot/optimize/config/SS-P.csv | tee results/SS-P.csv

python3.12 extend4.py ../../moot/optimize/config/SS-T.csv | tee results/SS-T.csv
python3.12 extend4.py ../../moot/optimize/config/SS-Q.csv | tee results/SS-Q.csv
python3.12 extend4.py ../../moot/optimize/config/HSMGP_num.csv | tee results/HSMGP_num.csv
python3.12 extend4.py ../../moot/optimize/config/SS-R.csv | tee results/SS-R.csv
python3.12 extend4.py ../../moot/optimize/config/X264_AllMeasurements.csv | tee results/X264_AllMeasurements.csv
python3.12 extend4.py ../../moot/optimize/config/SS-V.csv | tee results/SS-V.csv
python3.12 extend4.py ../../moot/optimize/config/SS-M.csv | tee results/SS-M.csv
python3.12 extend4.py ../../moot/optimize/process/coc1000.csv | tee results/coc1000.csv
python3.12 extend4.py ../../moot/optimize/config/SS-U.csv | tee results/SS-U.csv
python3.12 extend4.py ../../moot/optimize/process/nasa93dem.csv | tee results/nasa93dem.csv
python3.12 extend4.py ../../moot/optimize/process/xomo_flight.csv | tee results/xomo_flight.csv
python3.12 extend4.py ../../moot/optimize/process/xomo_ground.csv | tee results/xomo_ground.csv
python3.12 extend4.py ../../moot/optimize/process/xomo_osp.csv | tee results/xomo_osp.csv
python3.12 extend4.py ../../moot/optimize/process/xomo_osp2.csv | tee results/xomo_osp2.csv
python3.12 extend4.py ../../moot/optimize/config/SQL_AllMeasurements.csv | tee results/SQL_AllMeasurements.csv

python3.12 extend4.py ../../moot/optimize/process/pom3a.csv | tee results/pom3a.csv
python3.12 extend4.py ../../moot/optimize/process/pom3b.csv | tee results/pom3b.csv
python3.12 extend4.py ../../moot/optimize/process/pom3c.csv | tee results/pom3c.csv
python3.12 extend4.py ../../moot/optimize/config/SS-X.csv | tee results/SS-X.csv

python3.12 extend4.py ../../moot/optimize/binary_config/billing10k.csv | tee results/billing10k.csv
python3.12 extend4.py ../../moot/optimize/binary_config/Scrum1k.csv | tee results/Scrum1k.csv
python3.12 extend4.py ../../moot/optimize/binary_config/Scrum10k.csv | tee results/Scrum10k.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FFM-125-25-0.50-SAT-1.csv | tee results/FFM-125-25-0.50-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FFM-250-50-0.50-SAT-1.csv | tee results/FFM-250-50-0.50-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FFM-500-100-0.50-SAT-1.csv | tee results/FFM-500-100-0.50-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FM-500-100-0.75-SAT-1.csv | tee results/FM-500-100-0.75-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FM-500-100-1.00-SAT-1.csv | tee results/FM-500-100-1.00-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FM-500-100-0.50-SAT-1.csv | tee results/FM-500-100-0.50-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FM-500-100-0.25-SAT-1.csv | tee results/FM-500-100-0.25-SAT-1.csv
python3.12 extend4.py ../../moot/optimize/binary_config/FFM-1000-200-0.50-SAT-1.csv | tee results/FFM-1000-200-0.50-SAT-1.csv

python3.12 extend4.py ../../moot/optimize/config/SS-W.csv | tee results/SS-W.csv
python3.12 extend4.py ../../moot/optimize/config/SS-N.csv | tee results/SS-N.csv
python3.12 extend4.py ../../moot/optimize/binary_config/Scrum100k.csv | tee results/Scrum100k.csv